# Generated by Django 4.2.16 on 2026-08-30 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_studentprofile_companyprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('department', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=255)),
                ('workMode', models.CharField(choices=[('ON_SITE', 'On-site'), ('REMOTE', 'Remote'), ('HYBRID', 'Hybrid')], max_length=20)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('durationWeeks', models.IntegerField(default=0)),
                ('slots', models.IntegerField()),
                ('slotsFilled', models.IntegerField(default=0)),
                ('applicationDeadline', models.DateField()),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('preferredSkills', models.JSONField(blank=True, default=list)),
                ('responsibilities', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('publishedAt', models.DateTimeField(blank=True, null=True)),
                ('reviewNote', models.TextField(blank=True, null=True)),
                ('approvedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_opportunities', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='users.companyprofile')),
            ],
        ),
    ]
