# Generated by Django 4.2.16 on 2026-08-30 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_studentprofile_companyprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('WITHDRAWN', 'Withdrawn'), ('COMPANY_REVIEW', 'Company Review'), ('COMPANY_REJECTED', 'Company Rejected'), ('UNIVERSITY_REVIEW', 'University Review'), ('UNIVERSITY_REJECTED', 'University Rejected'), ('UNIVERSITY_APPROVED', 'University Approved')], default='SUBMITTED', max_length=50)),
                ('coverLetter', models.TextField()),
                ('documentIds', models.JSONField(blank=True, default=list)),
                ('submittedAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('companyDecisionAt', models.DateTimeField(blank=True, null=True)),
                ('companyDecisionReason', models.TextField(blank=True, null=True)),
                ('universityDecisionAt', models.DateTimeField(blank=True, null=True)),
                ('universityDecisionReason', models.TextField(blank=True, null=True)),
                ('revisionRequested', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('workplaceSupervisorId', models.CharField(blank=True, max_length=255, null=True)),
                ('academicSupervisorId', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('TERMINATED', 'Terminated')], default='APPROVED', max_length=50)),
                ('approvedAt', models.DateTimeField(blank=True, null=True)),
                ('supervisorAssignedAt', models.DateTimeField(blank=True, null=True)),
                ('completedAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement', to='applications.application')),
                ('approvedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_placements', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='users.companyprofile')),
            ],
        ),
    ]
