# Generated by Django 4.2.16 on 2026-08-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerId', models.CharField(max_length=100)),
                ('ownerRole', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('CV', 'CV'), ('INSURANCE', 'Insurance'), ('LOGBOOK', 'Logbook'), ('REPORT', 'Report'), ('OTHER', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='documents/')),
                ('filename', models.CharField(max_length=255)),
                ('mimeType', models.CharField(max_length=100)),
                ('sizeBytes', models.IntegerField()),
                ('uploadedAt', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewedById', models.CharField(blank=True, max_length=100, null=True)),
                ('reviewedAt', models.DateTimeField(blank=True, null=True)),
                ('reviewComment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
