# Generated by Django 4.2.16 on 2026-08-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placementId', models.CharField(max_length=100)),
                ('studentId', models.CharField(max_length=100)),
                ('evaluatorId', models.CharField(max_length=100)),
                ('evaluatorRole', models.CharField(max_length=50)),
                ('technicalSkills', models.IntegerField(default=0)),
                ('communication', models.IntegerField(default=0)),
                ('workEthic', models.IntegerField(default=0)),
                ('initiative', models.IntegerField(default=0)),
                ('overallScore', models.IntegerField(default=0)),
                ('recommendation', models.CharField(max_length=100)),
                ('feedback', models.TextField()),
                ('locked', models.BooleanField(default=False)),
                ('lockedAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placementId', models.CharField(max_length=100)),
                ('studentId', models.CharField(max_length=100)),
                ('periodStart', models.DateField()),
                ('periodEnd', models.DateField()),
                ('activitiesCompleted', models.TextField()),
                ('skillsLearned', models.TextField()),
                ('challenges', models.TextField()),
                ('achievements', models.TextField()),
                ('nextGoals', models.TextField()),
                ('supervisorFeedback', models.TextField(blank=True, null=True)),
                ('reviewedById', models.CharField(blank=True, max_length=100, null=True)),
                ('reviewedAt', models.DateTimeField(blank=True, null=True)),
                ('submittedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupervisionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placementId', models.CharField(max_length=100)),
                ('supervisorId', models.CharField(max_length=100)),
                ('studentId', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('VIRTUAL', 'Virtual'), ('IN_PERSON', 'In Person')], max_length=20)),
                ('notes', models.TextField()),
                ('rating', models.IntegerField()),
                ('submitted', models.BooleanField(default=False)),
                ('submittedAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
