# Generated by Django 4.2.16 on 2026-08-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentprofile_companyprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('COMPANY', 'Company'), ('COORDINATOR', 'Coordinator'), ('SUPERVISOR', 'Supervisor'), ('ADMIN', 'Admin')], default='STUDENT', max_length=20),
        ),
    ]
