# Generated by Django 4.2.16 on 2026-09-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_workplacesupervisor_supervisorprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='registrationNumber',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
