# Generated by Django 4.2.16 on 2026-09-03 15:51

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actorId', models.CharField(max_length=50)),
                ('actorName', models.CharField(max_length=255)),
                ('actorRole', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('objectType', models.CharField(max_length=50)),
                ('objectId', models.CharField(max_length=50)),
                ('objectLabel', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
